/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.nimmsta.core;
import java.lang.*;
public class App {
    public void connection() {
       Connection connection = new Connection();
       DemoEventHandler event = new DemoEventHandler();
       connection.startEvent(event);

       boolean isRunning = true;
        // Prevent app from exiting
        while (isRunning) {
            try {
                Thread.sleep(30);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }

        // Call this before teardown of application to close HS 50 connection
        connection.close();
    }

    public static void main(String[] args) {
        new App().connection();
    }
}
